export declare enum ActionSdkCommand {
    CreateActionInstance = "CreateActionInstance",
    CreateActionInstanceWithRows = "CreateActionInstanceWithRows",
    GetActionInstance = "GetActionInstance",
    UpdateActionInstance = "UpdateActionInstance",
    DeleteActionInstance = "DeleteActionInstance",
    SendActionInstanceReminder = "SendActionInstanceReminder",
    CreateOrUpdateActionInstanceRows = "CreateOrUpdateActionInstanceRows",
    GetActionInstanceRow = "GetActionInstanceRow",
    GetActionInstanceRows = "GetActionInstanceRows",
    DeleteActionInstanceRow = "DeleteActionInstanceRow",
    GetActionInstanceSummary = "GetActionInstanceSummary",
    GetActionInstanceData = "GetActionInstanceData",
    GetActionInstanceNonResponoders = "GetActionInstanceNonResponoders",
    GetConversationMembers = "GetConversationMembers",
    GetConversationMembersCount = "GetConversationMembersCount",
    GetUserProfiles = "GetUserProfiles",
    GetUserProfilePhotos = "GetUserProfilePhotos",
    SetNavBarMenuItem = "SetNavBarMenuItem",
    UploadMedia = "UploadMedia",
    DismissScreen = "DismissScreen",
    GetCurrentContext = "GetCurrentContext",
    LogTelemetry = "LogTelemetry",
    GetLocalizedActionStrings = "GetLocalizedActionStrings",
    ShowDiagnosticView = "ShowDiagnosticView"
}
